### PR TITLE
Bugfix ISBN validation & trimming for API

### LINKED ISSUE #133: Searching by ISBN with empty spaces is causing the search to fail
Searching for a book by ISBN with empty spaces (e.g. when copying ISBNs containing white spaces) is causing the search to fail.
On performing the search empty spaces should be removed from the input automatically.

### PR DESCRIPTION
**Pull request by LuisMossburger**
**Description**
Closes #133.
Adds proper validation and trimming of ISBNs before sending it to API & respective error message.

**Affects**
Classes relating to ISBN retrieval.

**Notes for Reviewer**
Please review & comment/approve.

### CODE REVIEW

File: BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java [hunk 1]
```diff
@@ -131,28 +132,40 @@ public void receiveDetections(Detector.Detections<Barcode> detections) {
...
-    thread.start();
-
-    try {
-      thread.join();
-    } catch (Exception e) {
-      System.out.println(e);
-    }
+    String cleanIsbn = isbn.replaceAll("\\s", "");
+
+    if (dataValidation.isValidIsbn10or13(cleanIsbn)) {
```
Comment (xSabrina) [inline BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java:137]:
```suggestion
    if (DataValidation.isValidIsbn10or13(cleanIsbn)) {
```
Access the static method this way instead through an instance.

File: BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java [hunk 2]
```diff
@@ -131,28 +132,40 @@ public void receiveDetections(Detector.Detections<Barcode> detections) {
...
+      isbnRetriever = new IsbnRetriever(cleanIsbn);
+      System.out.println(isbnRetriever);
```
Comment (xSabrina) [inline BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java:139]:
```suggestion
```
If you do not need that system-print, you should remove it - otherwise: nevermind.

File: BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java [hunk 3]
```diff
@@ -131,28 +132,40 @@ public void receiveDetections(Detector.Detections<Barcode> detections) {
...
+      thread = new Thread(isbnRetriever);
+      thread.start();
+
+      try {
+        thread.join();
+      } catch (Exception e) {
+        System.out.println(e);
```
Comment (xSabrina) [inline BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java:146]:
```suggestion
        e.printStackTrace();
```
Replace the custom system-print with a printstacktrace for logging exceptions.

File: BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java [hunk 4]
```diff
@@ -91,25 +92,32 @@ private void closeFragmentAfterAdding() {
...
-        } catch (Exception e) {
-          System.out.println(e);
-        }
-
-        // retrieve metadata that was saved
-        Book book = isbnRetriever.getBook();
-        List<Author> authors = isbnRetriever.getAuthors();
-        if (book != null) {
-          handleAddBook(book, authors);
+        if (dataValidation.isValidIsbn10or13(textInput)) {
```
Comment (xSabrina) [inline BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java:99]:
```suggestion
        if (DataValidation.isValidIsbn10or13(textInput)) {
```
Access static method this way (without using separate instance of DataValidation.

File: BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java [hunk 5]
```diff
@@ -91,25 +92,32 @@ private void closeFragmentAfterAdding() {
...
+          isbnRetriever = new IsbnRetriever(searchFieldText.getText().toString());
+          thread = new Thread(isbnRetriever);
+          thread.start();
+
+          try {
+            thread.join();
+          } catch (Exception e) {
+            System.out.println(e);
```
Comment (xSabrina) [inline BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java:107]:
```suggestion
            e.printStackTrace();
```
Log exceptions by printStackTrace instead of custom system prints.

File: BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java (hunk 1 above)
Comment (LuisMossburger) [reply BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java:137]: Sure, didn't think of this - thanks!

File: BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java (hunk 2 above)
Comment (LuisMossburger) [reply BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java:139]: Done.

File: BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java (hunk 3 above)
Comment (LuisMossburger) [reply BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java:146]: Done.

File: BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java (hunk 4 above)
Comment (LuisMossburger) [reply BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java:99]: Sure, didn't think of this - thanks!

File: BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java (hunk 5 above)
Comment (LuisMossburger) [reply BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java:107]: Done.

File: BibBuddy/app/src/main/java/de/bibbuddy/IsbnRetriever.java [hunk 6]
```diff
@@ -26,7 +26,7 @@
    * @author Luis Moßburger
    */
   IsbnRetriever(String isbn) {
-    this.isbn = isbn;
+    this.isbn = isbn.replaceAll("-", "").replaceAll("\\s","");
```
Comment (xSabrina) [inline BibBuddy/app/src/main/java/de/bibbuddy/IsbnRetriever.java:29]:
```suggestion
    this.isbn = isbn.replaceAll("-", "").replaceAll("\\s", "");
```
There was a white space missing after the last ",".

Comment (LuisMossburger) [reply BibBuddy/app/src/main/java/de/bibbuddy/IsbnRetriever.java:29]: Done.

**Review by xSabrina — CHANGES_REQUESTED** [review]
ISBN search works perfectly fine now.
I only suggest some clean ups and fixing a checkstyle-error.

**Comment by LuisMossburger** [comment]
Thanks for the review, corrected everything as suggested!

**Review by xSabrina — APPROVED** [review]
The changes are ready to be merged now :)
