### PR TITLE
Share of BibTeX file -  Feature Adjustment (Bug fix #127)

### LINKED ISSUE #127: Adjust export features to fetch only text notes
As soon voice notes are implemented all export features need to be adjusted to exclude voice notes (means: fetch only text notes (noteType = 0) to export).

### PR DESCRIPTION
**Pull request by silvia-ivanova-github-rep**
Fixes Bug **#127 Adjust export features to fetch only text notes**

**Description**
The shared BibTeX-file now contains only text notes (no audio).

**Affects**
Export/ Sharing

**Notes for Reviewer**
Please review & comment/approve.

### CODE REVIEW

File: BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java [hunk 1]
```diff
@@ -181,16 +181,19 @@ private String getBibKey(Book book) {
 
   private String getBibNotesFromBook(Book book, NoteDao noteDao) {
     List<Long> notesList = noteDao.getAllNoteIdsForBook(book.getId());
+    NoteTypeLut noteType = NoteTypeLut.TEXT;
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java:184]:
```suggestion
```

File: BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java [hunk 2]
```diff
@@ -181,16 +181,19 @@ private String getBibKey(Book book) {
...
     StringBuilder allNotes = new StringBuilder();
 
-    if (!notesList.isEmpty()) {
+    if (!notesList.isEmpty() && noteType.getId() == 1) {
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java:187]: This is always true: noteType.getId() == 1. You don't make it dependent on a note item.
```suggestion
    if (!notesList.isEmpty()) {
```

Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java:187]: This is always true: noteType.getId() == 1. So it's redundant. You didn't make it dependent on a note item.
```suggestion
    if (!notesList.isEmpty()) {
```

Comment (silvia-ivanova-github-rep) [reply BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java:187]: What is the difference with the previous comment?

File: BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java (hunk 1 above)
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java:184]:
```suggestion
```

Comment (silvia-ivanova-github-rep) [reply BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java:184]: If I delete this line, do you have a suggestion about how can I get the text notes?

Comment (claudia3) [reply BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java:184]: In your old code you don't consider the text notes, because you only check if the NoteTypeLut enum NoteTypeLut.TEXT has the value 1. And this is always true. 

The NoteDao `public String findTextById(Long id)` method  should probably be updated.  Check if the `DatabaseHelper.NOTE_FILE_ID` has the same value as the NoteTypeLut.TEXT.

Comment (claudia3) [reply BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java:184]: Try this out right at the beginning of your function with your debugger and I hope you understand what I mean. The test variable in the debugger shows `test=true`.
```
    boolean test = NoteTypeLut.TEXT.getId() == 1;
```

Comment (silvia-ivanova-github-rep) [reply BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java]: > In your old code you don't consider the text notes types, because you only check if the NoteTypeLut enum NoteTypeLut.TEXT has the value 1. And this is always true.
> 
I am considering only text values, since the enum constructor is called only with parameter 1 that is a Text.

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java [hunk 3]
```diff
@@ -252,6 +252,8 @@ public boolean linkNoteWithBook(Long bookId, Long noteId) {
    * @return returns the notes text value
    */
   public String findTextById(Long id) {
+    NoteTypeLut noteType = NoteTypeLut.TEXT;
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java:255]: Currently this variable isn't used. Where in your code you check that the note is a text note?

Comment (silvia-ivanova-github-rep) [reply BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java:255]: Claudia, this is the way to call the constructor. 

1. It is called when the value is from type 1 (TEXT). Here is a source, in which the enum constructors are explained:
[http://tutorials.jenkov.com/java/enums.html](url)
2. It is unnecessary to check if the NoteTypeLut.TEXT is equal to DatabaseHelper.NOTE_FILE_ID because the first one is from type Integer and the second one is from Type String. Moreover, when calling the method findTextById() the constructor is called with a value of 1.

I will not change it since the sharing function works properly.

Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java:255]:
```suggestion
```

Comment (claudia3) [reply BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java:255]: line 186 is also not needed  `if (!notesList.isEmpty()) {` because if the size is 0 the loop will not be executed.

Comment (claudia3) [reply BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java:255]: The noteType variable is not used at all so you should remove it or use it. 
Please consider the note type when you select notes because it is not considered yet. 
Instead of this code
`List<Long> notesList = noteDao.getAllNoteIdsForBook(book.getId());`  
you should write a new function where you get only the noteIds of the Text notes e.g. `getTextNoteIdsForBook(book.getId())`.  
Otherwise I will not approve your code like this.

**Review by claudia3 — CHANGES_REQUESTED** [review]
Please have a look at my comments.

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java (hunk 3 above)
Comment (silvia-ivanova-github-rep) [reply BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java:255]: I tried your suggestions and the app crashes every time. For me, it works well now. If you want to use this variable, then please provide me an example of how to use it. By calling the NoteTypeLut.TEXT the id of the notes is set to 1(TEXT). This is also explained in multiple sources about enum constructors. If you want then you can write your changes here or push them in the branch.

Comment (claudia3) [reply BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java:255]: You don't know what I mean. Let's have a meeting sometime and discuss it there.

**Review by claudia3 — COMMENTED** [review]
I will change it myself.

**Review by claudia3 — COMMENTED** [review]
This is how you use the enum correctly. The code works and only the text notes are fetched.

**Review by claudia3 — APPROVED** [review]
Approve after discussion.
