### PR TITLE
Bug fix search audio

### LINKED ISSUE #161: Display of audio notes in search list
**Description**
When searching for audio notes, these are displayed with a heading like "Sprachnotiz vom dd.mm.yyyy hh:mm" and with the document icon. Upon clicking, the text editor opens. The question also is - how should audionotes be searchable? They do not have a title, so should they show up when searching for the data of their respective book?

**Expected behavior**
For audio notes, the list view item from other lists (like in book note fragment) should be used. The respective icon (R.drawable.audionote) should be used and the audionote should be playable in the search list.

**Reproduce**
Add a shelf, a book and an audio note. In the search fragment, search for "Sprach" - the note will now show up. With a click on it, the text editor opens.

### PR DESCRIPTION
**Pull request by claudia3**
**Description**
Closes #161.
User can't search for audio notes anymore. 

**Affects**
Search classes.

**Notes for Reviewer**
Please review & comment/approve

### CODE REVIEW

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java [hunk 1]
```diff
@@ -254,7 +254,7 @@ public String findTextById(Long id) {
             DatabaseHelper.TYPE, DatabaseHelper.TEXT,
             DatabaseHelper.CREATE_DATE, DatabaseHelper.MOD_DATE,
             DatabaseHelper.NOTE_FILE_ID},
-        DatabaseHelper._ID + "=?", new String[] {String.valueOf(id)},
+        DatabaseHelper._ID + " = ?", new String[] {String.valueOf(id)},
```
Comment (silvia-ivanova-github-rep) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java:257]: In line 369 is used `"= ?"` without empty strings. Can you please change it like here, so that all are the same?

**Review by silvia-ivanova-github-rep — COMMENTED** [review]
Please take a look at the comment.

**Review by silvia-ivanova-github-rep — CHANGES_REQUESTED** [review]
Please take a look at the comments.

**Review by silvia-ivanova-github-rep — APPROVED** [review]
Thanks for the effort. I will approve and you can merge it.
