### PR TITLE
Bug fix text editor

### LINKED ISSUE #68: Fix bugs related to the text note editor
There are some small adjustments or bug fixes related to the text note editor and its features to do:

1. Currently whenever typing in the text note editor (or basically when **System UI displays the keyboard**) the **bottom navigation view is layed above it** and takes a lot of vertical space from the writing area - I suggest to avoid displaying the bottom navigation whenever the keyboard is shown - maybe by fetching the keyboard visibility and adjust visibility of the bottom navigation view to it in the MainActivity?

2. **Editing notes** is causing to save the edited version **as new note item** - adjust the way notes are saved.

3. **Editing notes** is not fetching/displaying the already existing text content.

4. There is a bug whenever **applying and deapplying bullets** that is causing the app to crash.

5. There is a bug whenever **applying and deapplying alignments**.

6. **Switching between selected alignments** that exclude each other is not working correctly (highlight and select the icon view).

### PR DESCRIPTION
**Pull request by xSabrina**
### Description

Closes #68  

Some bugs related to the text editor have been fixed and some small adjustments were done as well.

1. **Edited existing notes** were **saved as new notes** and their **already existing content was missing** - this is fixed now by adjusting the bundle that is given from the NoteRecyclerViewAdapter to the TextNoteEditorFragment (BTW: for editing notes from the book-views this needs to be done analogous).

2. There was a bug whenever **applying and deapplying alignments** - this is working fine now.

3. **Switching between selected alignments** that should exclude each other is working fine now (highlight and select the icon view and unhighlight and deselect others meanwhile).

4. **Applying and deapplying bullets** caused the app to **crash** - this is fixed as well.

5. **Bottom navigation view was always layed above soft-keyboard** (from SystemUI), which took a lot of vertical space - to avoid that the way the navigation view is layed out has been changed, so the keyboard will simply overlap it.

6. Also **adjusted the cursor position** to match the applied text alignment whenever inserting a new line.

7. **Besides: some small clean ups** mainly to RichTextEditor and TextNoteEditorFragment.

### Affects
Mainly the Text Editor functionality, which is also affecting the BookNotesRecyclerView (because notes are created here and existing ones are editable, which needs the TextNoteEditor), and therefore @SarahKurek should take a look. As some parts are also concern the UI, it might be interesting for @LuisMossburger as well.

### Notes for Reviewer

Edit an existing note from the NotesFragment (overall view for the notes) since the functionality for the BookView is not adjusted yet.

Please review & comment/approve.

### CODE REVIEW

**Comment by claudia3** [comment]
- When you edit a note and open the menu it seems to overlap with your first line. You should add a marginTop to your layout or something similar. 

- It is just my own opinion but I don't like the pink color when you select a note. You can't read the text really well. I would prefer another color where you can read the text better. You should **use** my **color selector** **or modify** it, so that the item **colors** are **consistent** for the app. The background of the items depends on the selected state of e.g. a note item (for code see my own in "res/color/library_item_selector.xml" (definition) and "list_view_item_library.xml" (usage in line 10) (card_view:cardBackgroundColor="@color/library_item_selector")). If you do that you don't need to set the background manually in your code. If the item is selected it will show the given color in the style if not it shows your other defined color. E.g. in "NoteRecyclerViewAdapter.java" you could remove the lines 113 and 116 if you use a color selector. It saves time and trouble to correctly adapt the colors depending on the state.

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java [hunk 1]
```diff
@@ -84,13 +84,15 @@ public MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
   @Override
   public void onBindViewHolder(@NonNull MyViewHolder holder, int position) {
     Long id = data.get(position).getId();
+    String text = noteModel.getNoteById(id).getText();
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java:87]: - Why is the noteModel in the NoteRecyclerViewAdapter? The model and the view should be separated and controlled by the Fragment. The NoteRecyclerViewAdapter should know nothing about the model. It should use the noteList from the NotesFragment when created, have a look at the other adapters. 

- The rest of the code looks fine to me.

**Review by claudia3 — CHANGES_REQUESTED** [review]

**Comment by xSabrina** [comment]
>     * When you edit a note and open the menu it seems to overlap with your first line. You should add a marginTop to your layout or something similar.

This was resolved in our weekly team meeting today already.

>     * It is just my own opinion but I don't like the pink color when you select a note. You can't read the text really well. I would prefer another color where you can read the text better. You should **use** my **color selector** **or modify** it, so that the item **colors** are **consistent** for the app.

I agree - done.

> The background of the items depends on the selected state of e.g. a note item (for code see my own in "res/color/library_item_selector.xml" (definition) and "list_view_item_library.xml" (usage in line 10) (card_view:cardBackgroundColor="@color/library_item_selector")). If you do that you don't need to set the background manually in your code. If the item is selected it will show the given color in the style if not it shows your other defined color. E.g. in "NoteRecyclerViewAdapter.java" you could remove the lines 113 and 116 if you use a color selector. It saves time and trouble to correctly adapt the colors depending on the state.

This is great - thank you very much - this is done as well and also applied that procedure to the way format options are highlighted in the text note editor.

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java (hunk 1 above)
Comment (xSabrina) [reply BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java]: This was a workaround since the adapter needs to fetch and provide the note text to the TextEditor, but NoteItems did not contain a text yet and name is not identical, but only it's first line. 
This is causing trouble as well since the adapter needs to delete notes as well as the noteItems on swipe left or on select and using the delete-panel.

The noteModel-usages have been removed from the adapter though - I adjusted the NoteItems to contain a text parameter. The actual deletion of notes as view and as data from the database is done through the NotesFragment with a noteModel.

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteModel.java [hunk 2]
```diff
@@ -86,13 +86,14 @@ private String getDate(Long date) {
       Long noteId = note.getId();
       String modDate = getDate(note.getModDate());
       String name = "";
+      String text = note.getText();
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteModel.java:89]:
```suggestion
```

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteModel.java [hunk 3]
```diff
@@ -86,13 +86,14 @@ private String getDate(Long date) {
...
       if (note.getType() == 0) {
         name = note.getName();
         name = Jsoup.parse(name).text();
         if (name.length() > 40) {
           name = name.substring(0, 35) + " ...";
         }
-        noteItemList.add(new NoteTextItem(modDate, name, noteId));
+        noteItemList.add(new NoteTextItem(modDate, name, text, noteId));
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteModel.java:96]: You don't need to create a local variable for text. 
```suggestion
        noteItemList.add(new NoteTextItem(modDate, name, note.getText(), noteId));
```

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java [hunk 4]
```diff
@@ -67,81 +59,61 @@ public MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
...
-            .commit();
-      }
+    holder.itemView.setOnClickListener(v -> {
+      TextNoteEditorFragment nextFrag = new TextNoteEditorFragment();
+      Bundle args = new Bundle();
+      args.putLong(LibraryKeys.NOTE_ID, id);
+      args.putString(LibraryKeys.NOTE_TEXT, text);
+      nextFrag.setArguments(args);
+      activity.getSupportFragmentManager().beginTransaction()
+          .replace(R.id.fragment_container_view, nextFrag, "fragment_text_note_editor")
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java:85]: You should use a constant variable for the "fragment_text_note_editor" tag.

File: BibBuddy/app/src/main/res/color/editor_toolbar_selector.xml [hunk 5]
```diff
@@ -0,0 +1,7 @@
+<?xml version="1.0" encoding="utf-8"?>
+<selector xmlns:android="http://schemas.android.com/apk/res/android">
+    <item android:color="@color/flirt_light" android:state_pressed="true" />
+    <item android:color="@color/flirt_light" android:state_selected="true" />
+    <item android:color="@color/flirt_light" android:state_checked="true" />
+    <item android:color="@color/flirt_dark" /> <!-- default -->
+</selector>
```
Comment (claudia3) [inline BibBuddy/app/src/main/res/color/editor_toolbar_selector.xml:7]: Please add a newline at the end of the file
```suggestion
</selector>

```

**Review by claudia3 — COMMENTED** [review]
I recommend the changes above. The rest looks good to me.

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java (hunk 4 above)
Comment (xSabrina) [reply BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java:85]: Thanks - this is done.

**Review by xSabrina — COMMENTED** [review]
Some small adjustments were done.

**Comment by xSabrina** [comment]
> 
> 
> I recommend the changes above.

Done.

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java [hunk 6]
```diff
@@ -67,81 +59,61 @@ public MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
...
-        TextNoteEditorFragment nextFrag = new TextNoteEditorFragment();
-        Bundle args = new Bundle();
-        args.putLong(LibraryKeys.NOTE_ID, id);
-        nextFrag.setArguments(args);
-        activity.getSupportFragmentManager().beginTransaction()
-            .replace(R.id.fragment_container_view, nextFrag, "fragment_text_note_editor")
-            .addToBackStack(null)
-            .commit();
-      }
+    holder.itemView.setOnClickListener(v -> {
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java:78]: Please add a newline for better readability.
```suggestion

    holder.itemView.setOnClickListener(v -> {
```

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java [hunk 7]
```diff
@@ -67,81 +59,61 @@ public MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
...
-        }
-        slideUpOrDown();
-        return true;
+    holder.itemView.setOnLongClickListener(v -> {
+      if (position == RecyclerView.NO_POSITION) {
+        return false;
       }
+      v.setSelected(!v.isSelected());
+      slideUpOrDown();
+      return true;
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java:95]:
```suggestion

      return true;
```

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java [hunk 8]
```diff
@@ -67,81 +59,61 @@ public MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
     Context context = parent.getContext();
     itemView =
         LayoutInflater.from(context).inflate(R.layout.list_view_item_note, parent, false);
-    background = itemView.getBackground();
     hiddenDeletePanel = parent.getRootView().findViewById(R.id.hidden_delete_panel);
     panelDelete = hiddenDeletePanel.findViewById(R.id.panel_delete);
     return new MyViewHolder(itemView);
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java:64]: Newline for better readability.
```suggestion

    return new MyViewHolder(itemView);
```

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java [hunk 9]
```diff
@@ -67,81 +59,61 @@ public MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
...
-        if (!v.isSelected()) {
-          v.setSelected(true);
-          v.setBackgroundColor(activity.getColor(R.color.flirt_light));
-        } else {
-          v.setSelected(false);
-          v.setBackground(background);
-        }
-        slideUpOrDown();
-        return true;
+    holder.itemView.setOnLongClickListener(v -> {
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java:89]: Newline for better readability.
```suggestion

    holder.itemView.setOnLongClickListener(v -> {
```

**Review by xSabrina — COMMENTED** [review]
Done.

**Review by xSabrina — COMMENTED** [review]
Done.

**Comment by claudia3** [comment]
When you create a lot of notes the bottom navigation bar is overlapped. Will this be changed in the next PR? You mentioned something like that to me before.

**Comment by claudia3** [comment]
Problem above resolved in a small discussion

**Review by claudia3 — APPROVED** [review]
The changes will be made in another PR.
