### PR TITLE
Fix overlapping note items (see Issue #146)

### LINKED ISSUE #146: Overlapping audio and text notes when deleted
When an audio file is deleted the view overlaps with a text note. The same happens in the Notes Screen where all notes are listed.
Screenshot_20210330_180720

### PR DESCRIPTION
**Pull request by SarahKurek**
**Description**
Closes #146.
Fixing the overlapping NoteItems after deleting an item. Visibility of the Note Audio elements was corrected. 
The existing enum was used for the NoteType so that there are no magic numbers in the code and errors are avoided. 
Also the code has been cleaned up a bit.

**Affects**
NotesFragment, BookNotesView, NoteTypeLut

**Notes for Reviewer**
Please review & comment/approve. Thanks!

### CODE REVIEW

File: BibBuddy/app/src/main/java/de/bibbuddy/NoteTextItem.java [hunk 1]
```diff
@@ -8,8 +10,31 @@
...
+
+  /**
+   * Constructor to set up a new noteTextItem.
+   *
+   * @param note   note object
+   * @param bookId id of the related book
+   */
+  public NoteTextItem(Note note, Long bookId) {
+    super(note, R.drawable.document, bookId);
+
```
Comment (claudia3) [inline BibBuddy/app/src/main/java/de/bibbuddy/NoteTextItem.java:23]:
```suggestion
```

**Review by claudia3 — APPROVED** [review]
